# Import Libraries


In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.special

# Neural Network class definition

### The Skeleton Code

- initialisation - to set the number of input, hidden and output nodes
- train - refine the weights after being given a training set example to learn from
- query - give an answer from the output nodes after being given an input


In [2]:
class NeuralNetwork:
    # initialise the neural network
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.inodes = input_nodes
        self.hnodes = hidden_nodes
        self.onodes = output_nodes
        self.lr = learning_rate

        # generate weights between input and hidden layers
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc
        self.wih = np.random.normal(
            0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes)
        )
        self.who = np.random.normal(
            0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes)
        )

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)

    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert targets list to 2d array
        targets = np.array(targets_list, ndmin=2).T

        # do all the things in query()
        final_outputs = self.query(inputs_list)

        # output = target - actual
        output_errors = targets - final_outputs

        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.who.T, output_errors)

    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T

        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)

        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)

        return final_outputs


### Create Instance


In [3]:
# set the number of each node in the neural network and its learning rate
input_nodes, hidden_nodes, output_nodes, learning_rate = 3, 3, 3, 0.3

# create neural network instance
n = NeuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)


## Class definition (step by step)


### `__init__` function

#### Generate Weights


In [4]:
np.random.rand(n.hnodes, n.inodes) - 0.5


array([[ 0.21496587, -0.38112296,  0.12055561],
       [-0.09222426,  0.32868435, -0.40992789],
       [ 0.21708426, -0.18055473,  0.35712912]])

**Optional**:

- 0.0 is the center of the normal distribution
- pow(n.hnodes, -0.5) is the standart deviation
- (n.hnodes, n.inodes) is the matrix size


In [5]:
# optional
np.random.normal(0.0, pow(n.hnodes, -0.5), (n.hnodes, n.inodes))


array([[ 0.77070279,  0.4365577 , -0.42568134],
       [-0.91969415,  0.33696156,  0.9651306 ],
       [-0.64848499,  0.39602342,  0.75982051]])

### `query` Function

Xhidden = Winput_hidden · I


In [6]:
inputs_list = np.random.rand(1, 3)
inputs = np.array(inputs_list, ndmin=2).T
inputs


array([[0.66119433],
       [0.28756881],
       [0.50984389]])

In [7]:
hidden_inputs = np.dot(n.wih, inputs)


expit() from scipy.special is used to calculate the sigmoid function

> `activation_function = lambda x: scipy.special.expit(x)`


In [8]:
# calculate the signals emerging from hidden layer
hidden_output = n.activation_function(hidden_inputs)


### Testing progress so far


In [9]:
n.query([1, 0.5, -1.5])


array([[0.5618877 ],
       [0.33223337],
       [0.30040386]])

### `train` Function


- started with the same code as `query()`
- *error = target - actual*
  - > `output_errors = targets - final_outputs`