# Import Libraries


In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.special

# Neural Network class definition

### The Skeleton Code

- initialisation - to set the number of input, hidden and output nodes
- train - refine the weights after being given a training set example to learn from
- query - give an answer from the output nodes after being given an input


In [3]:
class NeuralNetwork:
    # initialise the neural network
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        self.inodes = input_nodes
        self.hnodes = hidden_nodes
        self.onodes = output_nodes
        self.lr = learning_rate

        # generate weights between input and hidden layers
        # link weight matrices, wih and who
        # weights inside the arrays are w_i_j, where link is from node i to node j in the next layer
        # w11 w21
        # w12 w22 etc
        self.wih = np.random.normal(
            0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes)
        )
        self.who = np.random.normal(
            0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes)
        )

        # activation function is the sigmoid function
        self.activation_function = lambda x: scipy.special.expit(x)

    # train the neural network
    def train(self, inputs_list, targets_list):
        # convert targets list to 2d array
        targets = np.array(targets_list, ndmin=2).T

        # do all the things in query()
        final_outputs = self.query(inputs_list)

        # output = target - actual
        output_errors = targets - final_outputs

        # hidden layer error is the output_errors, split by weights, recombined at hidden nodes
        hidden_errors = np.dot(self.who.T, output_errors)

    # query the neural network
    def query(self, inputs_list):
        # convert inputs list to 2d array
        inputs = np.array(inputs_list, ndmin=2).T

        # calculate signals into hidden layer
        hidden_inputs = np.dot(self.wih, inputs)
        # calculate the signals emerging from hidden layer
        hidden_outputs = self.activation_function(hidden_inputs)

        # calculate signals into final output layer
        final_inputs = np.dot(self.who, hidden_outputs)
        # calculate the signals emerging from final output layer
        final_outputs = self.activation_function(final_inputs)

        return final_outputs


### Create Instance


In [4]:
# set the number of each node in the neural network and its learning rate
input_nodes, hidden_nodes, output_nodes, learning_rate = 3, 3, 3, 0.3

# create neural network instance
n = NeuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)


## Class definition (step by step)


### `__init__` function

#### Generate Weights


In [5]:
np.random.rand(n.hnodes, n.inodes) - 0.5


array([[-0.20799726, -0.27473704, -0.21492996],
       [-0.1150096 , -0.01479417,  0.04469106],
       [-0.44027702,  0.22765065,  0.28790455]])

**Optional**:

- 0.0 is the center of the normal distribution
- pow(n.hnodes, -0.5) is the standart deviation
- (n.hnodes, n.inodes) is the matrix size


In [6]:
# optional
np.random.normal(0.0, pow(n.hnodes, -0.5), (n.hnodes, n.inodes))


array([[-1.00634615,  0.14724881, -0.13815814],
       [-0.34078351,  1.22334995,  0.68420369],
       [ 0.47260433,  0.82160746, -0.18183479]])

### `query` Function

Xhidden = Winput_hidden · I


In [7]:
inputs_list = np.random.rand(1, 3)
inputs = np.array(inputs_list, ndmin=2).T
inputs


array([[0.31488012],
       [0.54812187],
       [0.82077763]])

In [8]:
hidden_inputs = np.dot(n.wih, inputs)


expit() from scipy.special is used to calculate the sigmoid function

> `activation_function = lambda x: scipy.special.expit(x)`


In [9]:
# calculate the signals emerging from hidden layer
hidden_output = n.activation_function(hidden_inputs)


### Testing progress so far


In [10]:
n.query([1, 0.5, -1.5])


array([[0.48298805],
       [0.57400857],
       [0.4521317 ]])

### `train` Function


- started with the same code as `query()`
- *error = target - actual*
  - > `output_errors = targets - final_outputs`